services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本，将 ./scripts/mysql/ 映射到 docker 内部执行
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      # 不需要密码
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  etcd:
    image: 'quay.io/coreos/etcd:v3.6.12'
    command:
      - etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "12379:2379"

  mongo:
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"