apiVersion: v1
kind: PersistentVolume
metadata:
  # 这个名字完全随便写，没有任何关联事件
  name: my-local-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/byline"
  