// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/JaylanCharles/byline/interactive/repository"
	"github.com/JaylanCharles/byline/interactive/repository/cache"
	"github.com/JaylanCharles/byline/interactive/repository/dao"
	"github.com/JaylanCharles/byline/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitInteractiveService() service.InteractiveService {
	db := InitDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	logger := InitLogger()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger)
	return interactiveService
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitLogger,
	InitRedis,
	InitDB,
)

var interactiveServiceSet = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
